version: '3'

services:
  endpoint-kafka:
    container_name: endpoint-kafka
    build:
      context: ./target
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    image: endpoint-kafka:latest
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
      KAFKA_STREAMING_QUEUE: si.test.queue
      KAFKA_RULE_QUEUE: si.ceprule.queue
      JAR_NAME: RestEndPointKafka-0.0.1-SNAPSHOT.jar
    networks:
      - broker-kafka

networks:
  broker-kafka:
    external: true